ITEM.name = "Большой ящик"
ITEM.desc = "Сюда поместится десяток краснолюдов!"
ITEM.model = "models/props/furnitures/humans/chests/cratea_medium3.mdl"
ITEM.width = 4
ITEM.height = 4
ITEM.invW = 8
ITEM.invH = 8
ITEM.locksound = "hgn/crussaria/devices/door_regular_stopclose.wav"
ITEM.opensound = "hgn/crussaria/devices/door_regular_opening.wav"
