ITEM.name = "Большой деревянный сундук"
ITEM.desc = "Выполнен из красных пород древесины и обит железом."
ITEM.model = "models/woodenchest.mdl"
ITEM.width = 5
ITEM.height = 3
ITEM.invW = 7
ITEM.invH = 5
ITEM.locksound = "hgn/crussaria/devices/door_regular_stopclose.wav"
ITEM.opensound = "hgn/crussaria/devices/door_regular_opening.wav"
