ITEM.name = "Сундук"
ITEM.desc = "Простейший деревянный сундук."
ITEM.model = "models/container2.mdl"
ITEM.width = 4
ITEM.height = 2
ITEM.invW = 6
ITEM.invH = 4
ITEM.locksound = "hgn/crussaria/devices/door_regular_stopclose.wav"
ITEM.opensound = "hgn/crussaria/devices/door_regular_opening.wav"
