ITEM.name = "Богатый шкаф"
ITEM.desc = "Определенно, выполнен искусным плотником."
ITEM.model = "models/cabinets3.mdl"
ITEM.width = 5
ITEM.height = 8
ITEM.invW = 6
ITEM.invH = 5
ITEM.locksound = "hgn/crussaria/devices/door_regular_stopclose.wav"
ITEM.opensound = "hgn/crussaria/devices/door_regular_opening.wav"
