ITEM.name = "Богатый стол"
ITEM.desc = "Украшен красивейшей резьбой."
ITEM.model = "models/toussaint_desk.mdl"
ITEM.width = 5
ITEM.height = 4
ITEM.invW = 4
ITEM.invH = 1
ITEM.locksound = "hgn/crussaria/devices/door_regular_stopclose.wav"
ITEM.opensound = "hgn/crussaria/devices/door_regular_opening.wav"
