ITEM.name = "Сундук со Скеллиге"
ITEM.desc = "Ввиду своей компактности и дешевизны, часто используется на драккарах островитян."
ITEM.model = "models/drakkarchest.mdl"
ITEM.width = 4
ITEM.height = 2
ITEM.invW = 5
ITEM.invH = 2
ITEM.locksound = "hgn/crussaria/devices/door_regular_stopclose.wav"
ITEM.opensound = "hgn/crussaria/devices/door_regular_opening.wav"
