ITEM.name = "Большой шкаф"
ITEM.desc = "Большой гардеробный шкаф, куда может вместиться порядка трех человек."
ITEM.model = "models/wardrobe.mdl"
ITEM.width = 4
ITEM.height = 6
ITEM.invW = 5
ITEM.invH = 7
ITEM.locksound = "hgn/crussaria/devices/door_regular_stopclose.wav"
ITEM.opensound = "hgn/crussaria/devices/door_regular_opening.wav"
