ITEM.name = "Вишнёвый сок"
ITEM.desc = "Кисловат."
ITEM.category = "Еда"
ITEM.model = "models/items/provisions/potions/life_potion.mdl"
ITEM.hunger = 0
ITEM.thirst = 50
ITEM.price = 40
ITEM.force = -15
ITEM.quantity = 4
ITEM.permit = "food"