ITEM.name = "Семена тыквы"
ITEM.model = "models/items/jewels/purses/big_purse.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.desc = "Небольшой мешочек с семенами тыквы."
ITEM.PlantModel = "models/aoc_trees/aoc_lowveg1.mdl"
ITEM.BadGathering = {"seed_pumpkin"}
ITEM.CommonGathering = {"seed_pumpkin","pumpkin"}
ITEM.MasterGathering = {"seed_pumpkin","seed_pumpkin","pumpkin"}