ITEM.name = "Семена пшеницы"
ITEM.model = "models/items/jewels/purses/big_purse.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.desc = "Небольшой мешочек с зерном."
ITEM.PlantModel = "models/aoc_trees/aoc_lowveg14.mdl"
ITEM.BadGathering = {"seed_wheat"}
ITEM.CommonGathering = {"seed_wheat","wheat"}
ITEM.MasterGathering = {"seed_wheat","seed_wheat","wheat"}