ITEM.name = "Хлеб"
ITEM.desc = "Уже зачерствел, но все еще пригоден в пищу."
ITEM.category = "Еда"
ITEM.model = "models/items/provisions/bread01/bread01_cooked.mdl"
ITEM.hunger = 40
ITEM.thirst = -15
ITEM.drunk = -15
ITEM.price = 35
ITEM.quantity = 5
ITEM.permit = "food"