ITEM.name = "Жареная козлятина"
ITEM.desc = "Хорошо прожаренное мясо козы. Или козла."
ITEM.category = "Еда"
ITEM.model = "models/items/provisions/ribs/ribs_cooked.mdl"
ITEM.hunger = 45
ITEM.thirst = 0
ITEM.price = 100
ITEM.quantity = 3
ITEM.permit = "food"