ITEM.name = "Омлет с колбасой и травами"
ITEM.desc = "Нежный и ароматный омлет с кусочками колбасы."
ITEM.category = "Еда"
ITEM.model = "models/items/provisions/pie/pie.mdl"
ITEM.hunger = 25
ITEM.thirst = 0
ITEM.price = 10
ITEM.quantity = 2
ITEM.permit = "food"