ITEM.name = "Пирог"
ITEM.desc = "Румяный пирог с вишней."
ITEM.category = "Еда"
ITEM.model = "models/items/provisions/pie/pie.mdl"
ITEM.hunger = 25
ITEM.thirst = 0
ITEM.price = 20
ITEM.quantity = 4
ITEM.permit = "food"