ITEM.name = "Тыква"
ITEM.desc = "Довольно большая."
ITEM.category = "Еда"
ITEM.model = "models/aoc_breakables/pumpkin_01.mdl"
ITEM.hunger = 15
ITEM.thirst = 10
ITEM.price = 20
ITEM.quantity = 4
ITEM.permit = "food"