ITEM.name = "Оленьи рёбра"
ITEM.desc = "Невероятно сочное блюдо."
ITEM.category = "Еда"
ITEM.model = "models/items/provisions/ribs/ribs_cooked.mdl"
ITEM.hunger = 45
ITEM.thirst = 0
ITEM.price = 45
ITEM.quantity = 5
ITEM.permit = "food"