ITEM.name = "Махакамская заливайка"
ITEM.desc = "Имеет невероятно приятный запах лесных грибов."
ITEM.category = "Еда"
ITEM.model = "models/plates7.mdl"
ITEM.hunger = 75
ITEM.empty = false
ITEM.thirst = 25
ITEM.quantity = 5
ITEM.emptyItem = "bowl"