ITEM.name = "Припарка"
ITEM.category = "Медицина"
ITEM.desc = "Целебная припарка, ускоряющая заживление ран"
ITEM.model = "models/items/jewels/purses/big_purse.mdl"
ITEM.price = 250
ITEM.permit = "med"
ITEM.healSeconds = 120
ITEM.health = 100
ITEM.sound = "physics/body/body_medium_impact_soft4.wav"
